version: "3.4"
services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: mysql:mysql@tcp(mysql:3306)/car_dev
    networks:
      - default
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: car_dev
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
    networks:
      - default
  dbMigrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      - -path=/migrations/
      - -database=mysql:mysql@tcp(mysql:3306)/car_dev
      - up
    depends_on:
      - mysql
    networks:
      - default

networks:
  default:
    name: dealership-default
