apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dealership-go-api.fullname" . }}
  labels:
    {{- include "dealership-go-api.labels" . | nindent 4 }}
  annotations: 
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production-v1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: dealership.selyslab.com
      http: 
        paths:
          - path: /api/car
            pathType: Prefix
            backend:
              service:
                name: {{ include "dealership-go-api.fullname" . }}
                port:
                  name: http
                 
  tls:
  - hosts:
    - dealership.selyslab.com
    secretName: dealership.selyslab.com-tls
