{{- if .Values.mysqlSecret.create}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysqlSecret.secretName}}
type: Opaque
data:
  {{ .Values.mysqlSecret.key }}: {{ printf "%s:%s@tcp(dealership-mysql:3306)/%s" .Values.mysql.auth.username .Values.mysql.auth.password .Values.mysql.auth.database | b64enc }}
{{- end}}